//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhongHocEntities : DbContext
    {
        public QLPhongHocEntities()
            : base("name=QLPhongHocEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbHeDT> tbHeDTs { get; set; }
        public virtual DbSet<tbHocKy> tbHocKies { get; set; }
        public virtual DbSet<tbHocKy_Mon> tbHocKy_Mon { get; set; }
        public virtual DbSet<tbKhoa> tbKhoas { get; set; }
        public virtual DbSet<tbLich_Hoc> tbLich_Hoc { get; set; }
        public virtual DbSet<tbLoaiTB> tbLoaiTBs { get; set; }
        public virtual DbSet<tbLop> tbLops { get; set; }
        public virtual DbSet<tbLop_Phong> tbLop_Phong { get; set; }
        public virtual DbSet<tbMonHoc> tbMonHocs { get; set; }
        public virtual DbSet<tbPhanBo> tbPhanBoes { get; set; }
        public virtual DbSet<tbPhongHoc> tbPhongHocs { get; set; }
        public virtual DbSet<tbTBHong> tbTBHongs { get; set; }
        public virtual DbSet<tbThietbi> tbThietbis { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
