//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHocKy_Mon
    {
        public int ID { get; set; }
        public int IDHocKy { get; set; }
        public int IDMonHoc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbHocKy tbHocKy { get; set; }
        public virtual tbMonHoc tbMonHoc { get; set; }
    }
}
