//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLop_Phong
    {
        public int ID { get; set; }
        public int IDLop { get; set; }
        public int IDPhongHoc { get; set; }
        public string NgayBanGiao { get; set; }
    
        public virtual tbLop tbLop { get; set; }
        public virtual tbPhongHoc tbPhongHoc { get; set; }
    }
}
