//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLop()
        {
            this.tbHocKies = new HashSet<tbHocKy>();
            this.tbLich_Hoc = new HashSet<tbLich_Hoc>();
            this.tbLop_Phong = new HashSet<tbLop_Phong>();
        }
    
        public int ID { get; set; }
        public string TenLop { get; set; }
        public string KhoaHoc { get; set; }
        public string GVCN { get; set; }
        public string GVTD { get; set; }
        public string NienKhoa { get; set; }
        public int IDHeDT { get; set; }
    
        public virtual tbHeDT tbHeDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHocKy> tbHocKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLich_Hoc> tbLich_Hoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLop_Phong> tbLop_Phong { get; set; }
    }
}
