//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMonHoc()
        {
            this.tbHocKy_Mon = new HashSet<tbHocKy_Mon>();
            this.tbLich_Hoc = new HashSet<tbLich_Hoc>();
            this.tbPhanBoes = new HashSet<tbPhanBo>();
        }
    
        public int ID { get; set; }
        public string TenMH { get; set; }
        public string KiHieuMH { get; set; }
        public int SoTiet { get; set; }
        public string GhiChu { get; set; }
        public int IDKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHocKy_Mon> tbHocKy_Mon { get; set; }
        public virtual tbKhoa tbKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLich_Hoc> tbLich_Hoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhanBo> tbPhanBoes { get; set; }
    }
}
