//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhongHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhongHoc()
        {
            this.tbLich_Hoc = new HashSet<tbLich_Hoc>();
            this.tbLop_Phong = new HashSet<tbLop_Phong>();
            this.tbThietbis = new HashSet<tbThietbi>();
        }
    
        public int ID { get; set; }
        public string TenPhong { get; set; }
        public string Tang { get; set; }
        public string Toa { get; set; }
        public int CoSo { get; set; }
        public Nullable<int> DienTich { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLich_Hoc> tbLich_Hoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLop_Phong> tbLop_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbThietbi> tbThietbis { get; set; }
    }
}
