//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhanBo
    {
        public int ID { get; set; }
        public int IDHeDT { get; set; }
        public int HocKy { get; set; }
        public int IDMon { get; set; }
    
        public virtual tbHeDT tbHeDT { get; set; }
        public virtual tbMonHoc tbMonHoc { get; set; }
    }
}
