//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTBHong
    {
        public int ID { get; set; }
        public int IDTB { get; set; }
        public string MoTaBaoHong { get; set; }
        public System.DateTime NgayBao { get; set; }
        public int IDNguoiBao { get; set; }
        public int TrangThai { get; set; }
        public int SoLuongBao { get; set; }
        public int SoLuongHong { get; set; }
        public int SoLuongSua { get; set; }
        public System.DateTime NgaySua { get; set; }
    
        public virtual tbThietbi tbThietbi { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
