//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Phonghoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbThietbi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbThietbi()
        {
            this.tbTBHongs = new HashSet<tbTBHong>();
        }
    
        public int ID { get; set; }
        public string TenTTB { get; set; }
        public int SoLuong { get; set; }
        public int IDLoaiTB { get; set; }
        public int IDPhongHoc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbLoaiTB tbLoaiTB { get; set; }
        public virtual tbPhongHoc tbPhongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTBHong> tbTBHongs { get; set; }
    }
}
